// <auto-generated />
using System;
using DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(QLKS_DA1_DbContext))]
    [Migration("20221109173933_addTienNghi_LoaiPhong")]
    partial class addTienNghi_LoaiPhong
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DAL.Models.ChiTietTienNghi", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDLoaiTienNghi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaCTTienNghi")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaCTTienNghi");

                    b.Property<string>("TenCTTienNghi")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("TenCTTienNghi");

                    b.HasKey("ID");

                    b.HasIndex("IDLoaiTienNghi");

                    b.ToTable("ChiTietTienNghi", (string)null);
                });

            modelBuilder.Entity("DAL.Models.ChucVu", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaCV")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaCV");

                    b.Property<string>("TenCV")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenCV");

                    b.HasKey("ID");

                    b.ToTable("ChucVu", (string)null);
                });

            modelBuilder.Entity("DAL.Models.LoaiPhong", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GiaNgay")
                        .HasColumnType("int")
                        .HasColumnName("GiayNgay");

                    b.Property<string>("MaLoaiPhong")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaLoaiPhong");

                    b.Property<int>("SoGiuong")
                        .HasColumnType("int")
                        .HasColumnName("SoGiuong");

                    b.Property<string>("TenLoaiPhong")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("TenLoaiPhong");

                    b.HasKey("ID");

                    b.ToTable("LoaiPhong", (string)null);
                });

            modelBuilder.Entity("DAL.Models.LoaiTienNghi", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaLoaiTienNghi")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaLoaiTienNghi");

                    b.Property<string>("TenLoaiTienNghi")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("TenLoaiTienNghi");

                    b.HasKey("ID");

                    b.ToTable("LoaiTienNghi", (string)null);
                });

            modelBuilder.Entity("DAL.Models.NhanVien", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("CCCD");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DiaChi");

                    b.Property<int>("GioiTinh")
                        .HasColumnType("int")
                        .HasColumnName("GioiTinh");

                    b.Property<Guid>("IDCv")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDCv");

                    b.Property<int>("Luong")
                        .HasColumnType("int")
                        .HasColumnName("Luong");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaNV");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime")
                        .HasColumnName("NgaySinh");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("SDT");

                    b.Property<string>("TenNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenNV");

                    b.HasKey("ID");

                    b.HasIndex("IDCv");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("DAL.Models.TaiKhoan", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CapDoQuyen")
                        .HasColumnType("int")
                        .HasColumnName("CapDoQuyen");

                    b.Property<Guid>("IDNv")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MatKhau");

                    b.Property<string>("TenTaiKhoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("TenTaiKhoan");

                    b.HasKey("ID");

                    b.HasIndex("IDNv")
                        .IsUnique();

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("DAL.Models.ChiTietTienNghi", b =>
                {
                    b.HasOne("DAL.Models.LoaiTienNghi", "LoaiTienNghi")
                        .WithMany()
                        .HasForeignKey("IDLoaiTienNghi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiTienNghi");
                });

            modelBuilder.Entity("DAL.Models.NhanVien", b =>
                {
                    b.HasOne("DAL.Models.ChucVu", "ChucVu")
                        .WithMany()
                        .HasForeignKey("IDCv")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChucVu");
                });

            modelBuilder.Entity("DAL.Models.TaiKhoan", b =>
                {
                    b.HasOne("DAL.Models.NhanVien", "NhanVien")
                        .WithOne("TaiKhoan")
                        .HasForeignKey("DAL.Models.TaiKhoan", "IDNv")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("DAL.Models.NhanVien", b =>
                {
                    b.Navigation("TaiKhoan")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
